/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    El_aside: typeof import('./src/components/Web_content/user_content/el_aside.vue')['default']
    El_footer: typeof import('./src/components/Web_content/user_content/el_footer.vue')['default']
    El_header: typeof import('./src/components/Web_content/user_content/el_header.vue')['default']
    El_main: typeof import('./src/components/Web_content/user_content/el_main.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Log_img: typeof import('./src/components/Web_content/user_content/log_img.vue')['default']
    My_log_in: typeof import('./src/components/Web_log/my_log_in.vue')['default']
    My_Pagination: typeof import('./src/components/Pagination/my_Pagination.vue')['default']
    My_sign_in: typeof import('./src/components/Web_log/my_sign_in.vue')['default']
    My_table: typeof import('./src/components/Web_content/my_table.vue')['default']
    My_test: typeof import('./src/components/my_test.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sign_Modal: typeof import('./src/components/Web_log/sign_Modal.vue')['default']
    User_content: typeof import('./src/components/Web_content/user_content/user_content.vue')['default']
    User_side_Images: typeof import('./src/components/Web_content/user_content/user_side_Images.vue')['default']
    Wang_Editer: typeof import('./src/components/Wang_Editer.vue')['default']
    Web_home: typeof import('./src/components/Web_content/Web_home.vue')['default']
    Web_signin: typeof import('./src/components/Web_log/Web_signin.vue')['default']
  }
}
